#NeosRulez:
#  Shop:
#    Finisher:
#      afterOrder:
#        customfinisher1:
#          class: NeosRulez\Shop\Service\Finisher\CustomFinisher
#      afterPayment:
#        customfinisher2:
#          class: NeosRulez\Shop\Service\Finisher\CustomFinisher

NeosRulez:
  Shop:
    Finisher:
      afterOrder:
        defaultOrderFinisher:
          class: NeosRulez\Shop\Service\OrderService
        defaultMailSendingFinisher:
          class: NeosRulez\Shop\Service\MailService
