Neos:
  Neos:
    modules:
      neosrulez_shop:
        label: 'Shop'
        controller: '\Neos\Neos\Controller\Module\ManagementController'
        description: 'Shop Administration'
        icon: 'icon-shopping-cart'
        resource: 'Neos_Neos_Backend_Module_Management'
        submodules:
          order:
            label: 'Bestellungen'
            controller: '\NeosRulez\Shop\Controller\OrderController'
            description: 'Verwalten Sie Ihre Bestellungen'
            icon: 'far fa-list-alt'
            actions:
              index:
                label: 'Bestellungen'
                title: 'Verwalten Sie Ihre Bestellungen'