Neos:
  Neos:
    nodeTypes:
      groups:
        neosrulez_shop:
          position: 'end'
          label: 'Shop'
    fusion:
      autoInclude:
        NeosRulez.Shop: true
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Shop:
            - 'NodeTypes/*'
            - 'NodeTypes/Content/*'
            - 'NodeTypes/Document/*'